/**
 * Explorer IDs (CORE)
 *
 * Explorer needs stable identifiers for nodes and moves inside a session.
 * We intentionally avoid crypto/randomUUID so the same code works in:
 * - Electron (Node)
 * - Angular (Browser)
 * - Unit tests
 *
 * IDs are generated by an incremental counter scoped to a session.
 */

export type ExplorerNodeId = string;

export type ExplorerIdFactory = {
	nextNodeId(): ExplorerNodeId;
};

export function createExplorerIdFactory(prefix = 'n'): ExplorerIdFactory {
	let counter = 0;

	return {
		nextNodeId(): ExplorerNodeId {
			counter += 1;
			return `${prefix}${counter}`;
		},
	};
}
