import type { ExternalSite } from '../../import/types';

/**
 * Import IPC contracts.
 *
 * This file is part of the **public ElectronApi surface** (used by preload + UI).
 *
 * Guidelines:
 * - Keep contracts stable and prefer additive changes.
 * - Dates are always raw ISO 8601 strings (UTC).
 * - Avoid importing runtime values here: types only.
 */

// -----------------------------------------------------------------------------
// Import v2 (start + streaming events)
// -----------------------------------------------------------------------------

/**
 * Input for starting an import batch.
 *
 * Notes:
 * - When all fields are omitted, the backend imports **all enabled accounts**
 *   using each account's `lastSyncAt` as the "since" cursor.
 * - `maxGamesPerAccount` is meant for debug/dev safety and should be treated as a
 *   best-effort cap (backend may still stop earlier).
 */
export interface ImportStartInput {
	/**
	 * If provided, overrides per-account lastSyncAt.
	 * ISO string (e.g. `new Date().toISOString()`).
	 */
	sinceOverrideIso?: string | null;

	/**
	 * If provided (>0), limits imported games per account (debug/dev).
	 */
	maxGamesPerAccount?: number | null;

	/**
	 * If provided, import only these account IDs.
	 * When null/undefined, the backend should import all enabled accounts.
	 */
	accountIds?: string[] | null;
}

export interface ImportStartResult {
	ok: true;

	/**
	 * Unique id for the running import batch.
	 * Generated by the Electron main process.
	 */
	batchId: string;

	/**
	 * Human-readable message for quick UI feedback.
	 * Examples: "Import started", "Import already running".
	 */
	message: string;
}

/**
 * Status returned for both account and batch completion.
 *
 * - SUCCESS: fully completed without errors.
 * - FAILED: unrecoverable error prevented completion.
 * - PARTIAL: completed but with errors for some items.
 */
export type ImportRunStatus = 'SUCCESS' | 'FAILED' | 'PARTIAL';

/**
 * Base payload for any import event.
 *
 * `emittedAtIso` is generated by Electron main to help ordering/debug (best-effort).
 */
export type ImportEventBase = {
	batchId: string;
	emittedAtIso: string;
};

/**
 * Streaming events emitted during an import batch.
 *
 * Notes:
 * - Events are best-effort and should not be assumed to be perfectly ordered.
 * - The UI should be resilient to missing intermediate events (e.g. progress jumps).
 */
export type ImportEvent =
	| (ImportEventBase & {
			type: 'runStarted';

			/** Echo of the resolved input (after any backend defaults). */
			sinceOverrideIso: string | null;
			maxGamesPerAccount: number | null;

			/**
			 * Planned account ids (when known), otherwise null.
			 * This can be used by the UI to pre-initialize account blocks.
			 */
			accountIds: string[] | null;
	  })
	| (ImportEventBase & {
			type: 'accountStarted';
			accountId: string;
			site: ExternalSite;
			username: string;
	  })
	| (ImportEventBase & {
			type: 'accountNewGamesFound';
			accountId: string;
			gamesFound: number;
	  })
	| (ImportEventBase & {
			type: 'accountProgress';
			accountId: string;

			/** Number of games processed so far for this account. */
			processed: number;

			/** Total new games to import for this account (X). */
			gamesFound: number;

			/** Per-account counters (must sum to `processed`). */
			inserted: number;
			skipped: number;
			failed: number;
	  })
	| (ImportEventBase & {
			type: 'accountError';
			accountId: string;

			/** External game id when available (Lichess id / Chess.com id). */
			externalId: string | null;

			/** Short error message intended for display. */
			message: string;
	  })
	| (ImportEventBase & {
			type: 'accountFinished';
			accountId: string;
			status: ImportRunStatus;

			gamesFound: number;
			inserted: number;
			skipped: number;
			failed: number;

			/** ISO timestamp emitted when this account finished processing. */
			finishedAtIso: string;
	  })
	| (ImportEventBase & {
			type: 'batchFinished';
			status: ImportRunStatus;

			totalGamesFound: number;
			totalInserted: number;
			totalSkipped: number;
			totalFailed: number;

			/** ISO timestamp emitted when the batch finished processing. */
			finishedAtIso: string;
	  });

export type ImportEventListener = (event: ImportEvent) => void;

/**
 * Subscription id returned by `onEvent()` and used with `offEvent()`.
 *
 * This is generated by the preload layer (renderer-side) and has no meaning in Electron main.
 */
export type ImportEventSubscriptionId = string;

// -----------------------------------------------------------------------------
// Public API exposed over IPC
// -----------------------------------------------------------------------------

/**
 * Import API exposed to the renderer via preload.
 *
 * Notes:
 * - `start` returns immediately; progress is delivered through event streaming.
 * - Methods are optional to keep the build green if a platform implementation is missing,
 *   but Electron builds are expected to implement all of them.
 */
export interface ImportApi {
	/**
	 * Start an import batch and return immediately.
	 * Progress is delivered through `onEvent()`.
	 */
	start?: (input?: ImportStartInput) => Promise<ImportStartResult>;

	/**
	 * Subscribe to import events (streamed from Electron main).
	 */
	onEvent?: (listener: ImportEventListener) => ImportEventSubscriptionId;

	/**
	 * Unsubscribe a previously registered event listener.
	 */
	offEvent?: (subscriptionId: ImportEventSubscriptionId) => void;
}
